### ISSUE TITLE
Timeout occurs when the namespace is created

### ISSUE THREAD

**Issue by growvv** [wzshiming/fake-k8s#110]
I want to use fake-k8s instead of kind for E2E testing, so I created a cluster named fake-cluster-c1
In the E2E testing framework, you need to use client go to create namespaces, node, pod and so on(yes, just like the E2E test of kubernetes).
```go
got, err = c.CoreV1().Namespaces().Create(context.TODO(), namespaceObj, metav1.CreateOptions{})
```
But this code is timeout.
Does fake-k8s not support client go operation？

**Comment by wzshiming** [comment]
fake-k8s only kubelet is part fake, I guess your connection is incorrectly configured?

**Comment by wzshiming** [comment]
``` console
➜  ~ KUBE_IMAGE_PREFIX=registry.aliyuncs.com/google_containers KUBE_VERSION=v1.24.1 fake-k8s create cluster
Creating cluster "fake-k8s-default"
Starting cluster "fake-k8s-default"
[+] Running 6/6
 ⠿ Network fake-k8s-default                            Created 0.1s
 ⠿ Container fake-k8s-default-etcd                     Started 1.3ss
 ⠿ Container fake-k8s-default-kube-apiserver           Started 1.9ss
 ⠿ Container fake-k8s-default-fake-kubelet             Started 3.2ss
 ⠿ Container fake-k8s-default-kube-scheduler           Started 3.0ss
 ⠿ Container fake-k8s-default-kube-controller-manager  Started 3.3ss
Wait for cluster "fake-k8s-default" to be ready
Cluster "fake-k8s-default" is ready
> kubectl --context fake-k8s-default get node
NAME     STATUS   ROLES   AGE   VERSION
fake-0   Ready    agent   0s    fake
fake-1   Ready    agent   0s    fake
fake-2   Ready    agent   0s    fake
fake-3   Ready    agent   0s    fake
fake-4   Ready    agent   0s    fake
➜  ~ kubectl --context fake-k8s-default apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: test
EOF
namespace/test created
➜  ~ kubectl --context fake-k8s-default  get ns -A
NAME              STATUS   AGE
default           Active   60s
kube-node-lease   Active   61s
kube-public       Active   61s
kube-system       Active   61s
test              Active   11s
```

That look works

**Comment by growvv** [comment]
Using the command line to create a namespace is no problem, and so am I
But I need to create namespace by client-go
In fact, this code is not written by me, but from the [kubernetes source code](https://github.com/kubernetes/kubernetes/blob/89aaf7c02dd33415ac994cecfddca7c02ed75834/test/e2e/framework/util.go#L375). 
Before I used kind for running E2E test, I didn't meet this problem. I don't know why.

**Comment by growvv** [comment]
If you have free time, I hope you write a document about how to run kubernetes E2E test with fake-k8s. Thank you very much

**Comment by wzshiming** [comment]
Maybe you need to run `kubectl config use fake-k8s-default`, then run e2e of Kubernetes.

I didn't run through e2E of Kubernetes with this, I don't know what effect it had.
